### ISSUE TITLE
Unable insert bundle (Bevy 0.7)

### ISSUE THREAD

**Issue by Semihazah** [Sliman4/bevy_slimy_widgets#1]
The compiler complains when I try to insert a TextInputBundle into an entity, saying that it does not implement bundle. It may be caused by the cargo.toml specifying Bevy 0.6 in the regular dependencies block.

**Comment by Sliman4** [comment]
Oh, when I was updating this to 0.7, I forgot to actually update bevy to 0.7 :man_facepalming:
